### ISSUE TITLE
Move from flat layout approach to src layout

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/sugar#91]
ref: https://osl-incubator.github.io/scicookie/guide.html#project-layout

**Comment by xmnlab** [comment]
As you can see, there is no `src ` folder. So, this is a flat layout, where typically source files are in a folder called with the same name of the package in the root of the project.

To convert that to src layout, basically:

1. Create a `src` folder in the root of the project
2. move `containers_sugar` to `src`
3. Update pyproject.toml

Verify in the code any place that is using the path `containers_sugar/` and replace by the new path

Some references: 
* https://github.com/arxlang/astx
* https://github.com/arxlang/astx/blob/main/pyproject.toml

**Comment by xmnlab** [comment]
Let me know if you need more details ou explanations please

**Comment by joel5vega** [comment]
I did the changes in this file:
![image](https://github.com/osl-incubator/containers-sugar/assets/27688744/c0df520a-c6fe-49f3-a6a9-7c4b23d2af44)
But I am not able to pass the precommit  stage.

![image](https://github.com/osl-incubator/containers-sugar/assets/27688744/5e8e41e8-d828-48c5-b577-7b0ade2ca8a6)
Checking with the examples it seems to have a similar configuration
![image](https://github.com/osl-incubator/containers-sugar/assets/27688744/441eb987-8219-4f31-af8f-bca0dd8b5439)
What can be the problem?

**Comment by xmnlab** [comment]
@joel5vega , we just merged a PR for the same purpose for makim here: https://github.com/osl-incubator/makim/pull/63/files
you can use that as a reference

**Comment by joel5vega** [comment]
![image](https://github.com/osl-incubator/containers-sugar/assets/27688744/0162a017-a871-4777-b4bb-d9024ea8c6b2)
I have updated this in commit 1580480 from my fork.
i think it will be visible in my next PR
